### ISSUE TITLE
Move performMove and validateCellSelection to new Java interface and Class named Phase

### ISSUE THREAD

**Issue by EXC3ll3NTrhyTHM** [CS-449-Group-Project/NineMensMorris#22]
performMove:
https://github.com/CS-449-Group-Project/NineMensMorris/blob/master/src/Morris_FX/Logic/GameManager.java#L27

validateCellSelection: 
https://github.com/CS-449-Group-Project/NineMensMorris/blob/master/src/Morris_FX/Logic/Board.java#L75

Java Interface tutorial: https://www.tutorialspoint.com/java/java_interfaces.htm

Task Description:

Create new interface and abstract class named `Phase`(reason we need new class is because interfaces cant have method implementations and I thought a new class would be the best place to have these method implementations) and move the methods `validateCellSelection` and `performMove` to this interface strictly as abstract methods. Next update the [onCellClick](https://github.com/CS-449-Group-Project/NineMensMorris/blob/master/src/Morris_FX/Ui/BoardPane.java#L57) method in BoardPane to use these newly defined methods(Im not totally sure how to do this part without a switch statement -Blake). This should be done first in one branch named PhaseUpdates and then for the three Phase extended classes we would branch off of PhaseUpdates.

Name the branches and Extend the `Phase` class to classes named `PiecePlacementPhase`, `PieceMovementPhase`, and `FlyRulePhase`. Add method implementations for `validateCellSelection` and `performMove` in these new classes. Each new method should have the actions performed in their corresponding `case` inside either `validateCellSelection ` or `performMove`'s `switch statement. 

Interface naming conventions discussion says no prefix for readability sake https://stackoverflow.com/questions/541912/interface-naming-in-java

**Comment by ahrayahlabcoimin** [comment]
onCellClick would still call `gameManager.performMove` and .`gameManager.validateCellSelection`. Can use a EnumMap to get the relevant phase for the current player in both methods.

**Comment by EXC3ll3NTrhyTHM** [comment]
@ahrayahlabcoimin okay so would that mean that those two methods would have implementations in the GameManager class? How would this class have access to those methods if their implementations are in a different class. I'm pretty new to interfaces so forgive me if I have a incomplete or incorrect understanding of them.

**Comment by ahrayahlabcoimin** [comment]
gameManager keeps track of phases and determines which phase is called.

**Comment by EXC3ll3NTrhyTHM** [comment]
Okay so it sounds like we keep `performMove` and `validateCellSelection` in `GameManager` and point those methods to the appropriate ones in the `Phase` classes depending on the phase, then call `gameManager.performMove` and `gameManager.validateCellSelection` from `onCellClick`?

**Comment by EXC3ll3NTrhyTHM** [comment]
And we will use an `EnumMap` variable of the `Player` class to keep track of the current phase for the player.

**Comment by ahrayahlabcoimin** [comment]
Yeah.

**Comment by EXC3ll3NTrhyTHM** [comment]
Once all updates are done we will need to make sure that throughout the code the new methods are being used and not the old implementations.
